services:
  backend:
    container_name: django
    build: .
    command: >
      sh -c "python manage.py makemigrations && 
             python manage.py migrate &&
             daphne -b 0.0.0.0 -p 8000 backend.asgi:application"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:{REDIS_PORT}"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data: